//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chitietgiaohang
    {
        public string Madonhang { get; set; }
        public Nullable<int> Gia { get; set; }
        public string Masanpham { get; set; }
        public Nullable<System.DateTime> ngaygiaohang { get; set; }
    
        public virtual Donhang Donhang { get; set; }
        public virtual Sanpham Sanpham { get; set; }
    }
}
