//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donhang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Donhang()
        {
            this.Nguoidungs = new HashSet<Nguoidung>();
            this.Quanlykhoes = new HashSet<Quanlykho>();
        }
    
        public string Madonhang { get; set; }
        public Nullable<int> Giatridonhang { get; set; }
        public string Thongtindonhang { get; set; }
    
        public virtual Chitietdonhang Chitietdonhang { get; set; }
        public virtual Chitietgiaohang Chitietgiaohang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nguoidung> Nguoidungs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quanlykho> Quanlykhoes { get; set; }
    }
}
