//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nguoidung
    {
        public string id { get; set; }
        public string Ho { get; set; }
        public string Ten { get; set; }
        public Nullable<System.DateTime> Ngaythangnamsinh { get; set; }
        public Nullable<int> Gioitinh { get; set; }
        public string Mail { get; set; }
        public string Diachi { get; set; }
        public string Sodienthoai { get; set; }
        public string Madonhang { get; set; }
        public string Trungbinhdanhgia { get; set; }
        public string Nhanxet { get; set; }
        public string Thongtinlienhe { get; set; }
        public string Tentaikhoan { get; set; }
        public string Magiohang { get; set; }
        public string Phuongthucthanhtoan { get; set; }
        public string Makhachhang { get; set; }
        public string Masanpham { get; set; }
    
        public virtual Donhang Donhang { get; set; }
        public virtual Giaohang Giaohang { get; set; }
        public virtual Giohang Giohang { get; set; }
        public virtual Sanpham Sanpham { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
        public virtual Thanhtoan Thanhtoan { get; set; }
    }
}
